COMP: Fix missing `s` in header license notice URL http link
Fix missing `s` in header license notice URL http link.

Fixes:
```
ITKRingArtifact/include/itkFourierStripeArtifactImageFilter.h:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt
 (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
ITKRingArtifact/include/itkFourierStripeArtifactImageFilter.hxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt
 (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
ITKRingArtifact/test/itkFourierStripeArtifactImageFilterTest.cxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt
 (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
```

raised for example at:
https://github.com/InsightSoftwareConsortium/ITKRingArtifact/actions/runs/9662460884/job/26652393725#step:14:60
and
https://github.com/InsightSoftwareConsortium/ITKRingArtifact/actions/runs/9663108489/job/26654482751?pr=10#step:14:60